### PR TITLE
Solo project - project #4 - apple-page clone

### PR DESCRIPTION
**Pull request by guirecordon**
**Apple Page Clone - Gradients and Background project**

In this project:

- I built a hero header using a background image followed by 4 promotion links with background images as well. 
- I centered all of the images using background positioning. I centered them at 50% from the left and 100% in the baseline. 
- The promotion links images were enveloped in a wrap-container with flex. I gave each of them a flex-basis of 25% and told them to shrink and grow at 1. This allowed all four images to be always on display and since the images were centered using background, they never got cropped, shrunk nor bloated off in undesired ways. 
- I added my main navigation bar to the top of the page and put it inside of the hero image container. Then, right beneath it, I added a wrap-container with a title header, a subheading and a call to action, all of which were background images. I just let all these elements stack vertically in the normal flow of the page and did not have to use any flex for that. 
- The navigation bar presented the perfect use case for the flexbox. I built a list of items, which all became flex items, and I told each item to take 100% of the width of their container. That allowed me to use borders that were also flexible. I also had a search bar inside of the nav-bar, and that search bar expanded on ": focus". So flex took care of all the size adjustments for me, which rendered an ideal user experience.  
-The background of the navigation bar was designed using gradients, and the text using the box-shadow property. 
-Finally, I added a footer inside of a flex container, which also came in handy when I had to align their items.  

Here's a link to the live demo: 
https://raw.githack.com/guirecordon/apple-page/solo-project/index.html

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for your full review

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Really wonderful job @guirecordon!
Your UI is exquisite :ok_hand:  please conside my comments below, make the appropriate change and request another review. I wish you all the best

#### Hero Section
Please consider the hero text in the screenshot below, it is chopped off towards the end of the hero section, likely due to the height property set on the section. Please look into this and it will make your page even more exquisite.
screenshot

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by guirecordon** [comment]
Hi, 
Thank you for your review. I just made the changes you pointed out, including a more descriptive PR with a live demo link included, as you can check out above.

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Project requires changes.

**Comment by pelzolga123** [comment]
## Hi Gui!  
#### Your project looks :+1: amazing!
Just a few more thing is left:
* [x] check HTML markup with this [validator](https://validator.w3.org/#validate_by_upload). Now it shows error in your project.
* [x] Your `.stickler.yml` file is present, but not checking your code. You need to make it work, before this project can be approved.  
#### [OPTIONAL]:
* Bottom part should contain four elements which are links (to other articles or #). Right now they are just four div's, but better to add links to them, just like on original website.

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by guirecordon** [comment]
Thank you so much, Olga, for being so helpful!

**Review by addod19 — APPROVED** [review]
## Status: Approved ✈️ 🎈 

Hi @guirecordon, **congratulations** on a great job done. You did all the changes requested by the previous reviewers. 👍 Your project has now met the minimum requirement to be approved 😄 **Congratulations** once again.
Before you merge to master and submit a project completion form, I have an optional comment below:
- Text hiding behind the four-link bottom. Check Image for more description
option

Good luck with your next submission 🏆 
Happy coding 💻 
Daniel Larbi Addo

**Comment by guirecordon** [comment]
Thank you, Daniel. I fixed the issue you mentioned with the hero image.

**Comment by guirecordon** [comment]
Thank you, Daniel. I fixed the problem with the hero image.

**Pull request merged**
